## numpy library

### Matrix(2d or 1d)

In [2]:
import numpy as np

In [4]:
simple_list = [1,2,3]
np.array(simple_list)

array([1, 2, 3])

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
dd_array = [1,2,3],[4,5,6],[7,8,9]
np.array(dd_array)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(37,50)

array([37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
np.arange(50,37)

array([], dtype=int32)

In [9]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(6,dtype=int)

array([1, 1, 1, 1, 1, 1])

In [14]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(2,4)

array([[0.99481122, 0.51505271, 0.85167107, 0.50596578],
       [0.94190202, 0.76429146, 0.44456545, 0.07811166]])

In [19]:
np.random.randn(2,4)

array([[-2.72506185, -0.67254706, -0.01672517, -0.97775029],
       [ 1.81150376, -0.29653309,  0.96268607, -1.95188793]])

In [20]:
np.random.randint(1,5,4)

array([1, 1, 4, 3])

In [21]:
sample = np.arange(1,10)
sample

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
random_array = np.random.randint(0,10,5)
random_array

array([9, 1, 8, 4, 1])

In [23]:
sample.min()

1

In [24]:
sample.argmin()

0

In [25]:
random_array.argmin()

1

In [26]:
random_array.argmax()

0

In [27]:
random_array.max()

9

In [28]:
sample.argmax()

8

In [29]:
sample.dtype

dtype('int32')

In [31]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a = np.random.rand(2,3)
a

array([[0.64067683, 0.69166462, 0.20337727],
       [0.08554923, 0.49955509, 0.68194945]])

In [33]:
a.T

array([[0.64067683, 0.08554923],
       [0.69166462, 0.49955509],
       [0.20337727, 0.68194945]])

In [34]:
sample=np.arange(10,28)
sample

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [35]:
sample = sample.reshape(6,3)
sample

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [36]:
sample = sample.reshape(3,4)
sample

ValueError: cannot reshape array of size 18 into shape (3,4)

In [37]:
sample[5]=100
sample

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [38]:
sample = np.arange(10,100)
sample

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [39]:
sample[2:10]

array([12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
subset_sample = sample[0:7]
subset_sample

array([10, 11, 12, 13, 14, 15, 16])

In [41]:
sample[1:5]=1001
sample

array([  10, 1001, 1001, 1001, 1001,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

## 2D Matrix

In [43]:
sample = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
sample

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
sample[2][2]

11

In [45]:
sample[1][3]

8

In [46]:
sample[:,3]

array([ 4,  8, 12])

In [47]:
sample[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [48]:
sample[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [49]:
sample[2]

array([ 9, 10, 11, 12])

In [51]:
sample=np.arange(1,31)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
sample+sample

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [53]:
np.exp(sample)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [54]:
np.sqrt(sample)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [55]:
np.log(sample)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [56]:
np.min(sample)

1

In [57]:
np.max(sample)

30

In [58]:
np.argmin(sample)

0

In [59]:
np.argmax(sample)

29

In [60]:
np.square(sample)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [61]:
np.std(sample)

8.65544144839919

In [62]:
np.var(sample)

74.91666666666667

In [63]:
np.mean(sample)

15.5

In [64]:
array = np.random.randn(3,4) ###normal distribution
array

array([[ 0.5137558 ,  0.17647326, -0.13857127,  1.1423091 ],
       [ 0.48016693,  0.28636959, -2.14547823,  0.7808661 ],
       [ 0.82701122,  0.17648628, -1.47504956,  2.0129581 ]])

In [65]:
np.round(array,decimals=3)

array([[ 0.514,  0.176, -0.139,  1.142],
       [ 0.48 ,  0.286, -2.145,  0.781],
       [ 0.827,  0.176, -1.475,  2.013]])

In [66]:
fruits=np.array(['apple','orange','pineapple','mango','apple','orange'])
np.unique(fruits)

array(['apple', 'mango', 'orange', 'pineapple'], dtype='<U9')

## Pandas

In [67]:
import pandas as pd
import numpy as np

In [69]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [70]:
sports2=pd.Series([1,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     1
football    2
baseball    3
golf        4
dtype: int64

In [71]:
sports1['basketball']

3

In [72]:
sports1+sports2

baseball      NaN
basketball    NaN
cricket       2.0
football      4.0
golf          8.0
dtype: float64

In [75]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.581604  0.428973  0.342458  0.326381  0.852085
B  0.159505  0.619404  0.240443  0.659646  0.653853
C  0.812789  0.740870  0.719754  0.285683  0.908122
D  0.771046  0.968748  0.349260  0.243499  0.775491
E  0.828356  0.060997  0.150674  0.604202  0.023229
F  0.279036  0.629787  0.165489  0.592591  0.976424
G  0.826161  0.919139  0.067633  0.056713  0.141137
H  0.689288  0.642471  0.116081  0.225881  0.775051

In [76]:
df1[['Score1','Score2','Score3']]

Score1    Score2    Score3
A  0.581604  0.428973  0.342458
B  0.159505  0.619404  0.240443
C  0.812789  0.740870  0.719754
D  0.771046  0.968748  0.349260
E  0.828356  0.060997  0.150674
F  0.279036  0.629787  0.165489
G  0.826161  0.919139  0.067633
H  0.689288  0.642471  0.116081

In [77]:
df1['Score2']

A    0.428973
B    0.619404
C    0.740870
D    0.968748
E    0.060997
F    0.629787
G    0.919139
H    0.642471
Name: Score2, dtype: float64

In [79]:
df1['Score6']=df1['Score1']+df1['Score1']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.581604  0.428973  0.342458  0.326381  0.852085  1.163208
B  0.159505  0.619404  0.240443  0.659646  0.653853  0.319010
C  0.812789  0.740870  0.719754  0.285683  0.908122  1.625579
D  0.771046  0.968748  0.349260  0.243499  0.775491  1.542092
E  0.828356  0.060997  0.150674  0.604202  0.023229  1.656712
F  0.279036  0.629787  0.165489  0.592591  0.976424  0.558071
G  0.826161  0.919139  0.067633  0.056713  0.141137  1.652322
H  0.689288  0.642471  0.116081  0.225881  0.775051  1.378577

In [80]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.581604  0.428973  0.342458  0.326381  0.852085  1.163208
B  0.159505  0.619404  0.240443  0.659646  0.653853  0.319010
C  0.812789  0.740870  0.719754  0.285683  0.908122  1.625579
D  0.771046  0.968748  0.349260  0.243499  0.775491  1.542092
F  0.279036  0.629787  0.165489  0.592591  0.976424  0.558071
G  0.826161  0.919139  0.067633  0.056713  0.141137  1.652322
H  0.689288  0.642471  0.116081  0.225881  0.775051  1.378577

In [81]:
df1.drop('Score1',axis=1)

Score2    Score3    Score4    Score5    Score6
A  0.428973  0.342458  0.326381  0.852085  1.163208
B  0.619404  0.240443  0.659646  0.653853  0.319010
C  0.740870  0.719754  0.285683  0.908122  1.625579
D  0.968748  0.349260  0.243499  0.775491  1.542092
E  0.060997  0.150674  0.604202  0.023229  1.656712
F  0.629787  0.165489  0.592591  0.976424  0.558071
G  0.919139  0.067633  0.056713  0.141137  1.652322
H  0.642471  0.116081  0.225881  0.775051  1.378577

In [82]:
df1.drop('A',axis=0)

Score1    Score2    Score3    Score4    Score5    Score6
B  0.159505  0.619404  0.240443  0.659646  0.653853  0.319010
C  0.812789  0.740870  0.719754  0.285683  0.908122  1.625579
D  0.771046  0.968748  0.349260  0.243499  0.775491  1.542092
E  0.828356  0.060997  0.150674  0.604202  0.023229  1.656712
F  0.279036  0.629787  0.165489  0.592591  0.976424  0.558071
G  0.826161  0.919139  0.067633  0.056713  0.141137  1.652322
H  0.689288  0.642471  0.116081  0.225881  0.775051  1.378577

In [83]:
df1.drop(['Score1','Score2'],axis=1)

Score3    Score4    Score5    Score6
A  0.342458  0.326381  0.852085  1.163208
B  0.240443  0.659646  0.653853  0.319010
C  0.719754  0.285683  0.908122  1.625579
D  0.349260  0.243499  0.775491  1.542092
E  0.150674  0.604202  0.023229  1.656712
F  0.165489  0.592591  0.976424  0.558071
G  0.067633  0.056713  0.141137  1.652322
H  0.116081  0.225881  0.775051  1.378577

In [84]:
df2={'ID':[101,102,103,107,16],'Name':['A','B','C','D','E',],'Profit':[1,2,3,4,5]}
df=pd.DataFrame(df2)
df

ID Name  Profit
0  101    A       1
1  102    B       2
2  103    C       3
3  107    D       4
4   16    E       5

In [85]:
df.drop('ID',axis=1)

Name  Profit
0    A       1
1    B       2
2    C       3
3    D       4
4    E       5

In [86]:
df.drop(3)

ID Name  Profit
0  101    A       1
1  102    B       2
2  103    C       3
4   16    E       5

In [87]:
df['Name']

0    A
1    B
2    C
3    D
4    E
Name: Name, dtype: object

In [88]:
df['Name','ID']

KeyError: ('Name', 'ID')

### Assessment


In [89]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
array=np.zeros(10,dtype=int)
array[4]=1
array

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [93]:
array=np.arange(10,66)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [95]:
array=np.arange(65,9,-1)
array

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [98]:
array=np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])